<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
    <ProjectReference Include="..\AgroControl.Application\AgroControl.Application.csproj" />
    <ProjectReference Include="..\AgroControl.Infrastructure\AgroControl.Infrastructure.csproj" />
    <ProjectReference Include="..\AgroControl.Contracts\AgroControl.Contracts.csproj" />
  </ItemGroup>
</Project>
